version: '3'
volumes:
  jenkins-data:

networks:
  jenkins:
    driver: bridge

services:
  jenkins:
    build:
      context: containers/jenkins
      dockerfile: Dockerfile
    image: oci.local/jenkins/server:lts
    container_name: jenkins
    networks:
      - jenkins
    ports:
      - 58080:8080/tcp
      - 50001:50001/tcp
    environment:
      JAVA_OPTS: "-Xmx2048m"
    volumes:
    - jenkins-data:/var/jenkins_home
  
  nginx:
    build:
      context: containers/nginx
      dockerfile: Dockerfile
    image: oci.local/jenkins/nginx:stable
    container_name: nginx
    depends_on:
      - jenkins
    networks:
      - jenkins
    ports:
      - 50080:80/tcp